- id: uncomment
  name: uncomment
  description: Prevents commits with comments-only code.
  entry: uncomment
  language: python
  types: [python]
  # for backward compatibility
  files: ""
  minimum_pre_commit_version: 0.15.0
